// action types
export const API_REQUEST = "API_REQUEST";
export const API_REQUEST_SUCCESS = "API_REQUEST_SUCCESS";
export const API_REQUEST_FAILURE = "API_REQUEST_FAILURE";
export const API_DELETE_CHARACTER = "API_DELETE_CHARACTER";
export const API_SET_CHARACTER_CARD_NAME = "API_SET_CHARACTER_CARD_NAME";
export const API_REMOVE_CHARACTER_CARD_NAME = "API_REMOVE_CHARACTER_CARD_NAME";